import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";

const myFont = localFont({
  src: [
    { path: '../../public/fonts/georama-regular.ttf', weight: '400', style: 'normal' },
    { path: '../../public/fonts/georama-semibold.ttf',  weight: '500', style: 'normal' },
    { path: '../../public/fonts/georama-extraBold.ttf',    weight: '700', style: 'normal' },
    { path: '../../public/fonts/georama-italic.ttf',    weight: '400', style: 'italic'},
  ],
  variable: '--font-georama',    // CSS variable we’ll hook into Tailwind
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${myFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
